name: CD-Examples

on:
  push:
    branches: [ develop-examples-app ]

jobs:
  deploy-to-github-pages:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2.3.3
      
    - name: Install .NET
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 5.0.100
     
    # changes the base-tag in index.html from '/' to '/Typin/' to match GitHub Pages repository subdirectory
    - name: Change base-tag in index.html from '/ to '/Typin/'
      run: sed -i 's/<base href="\/" \/>/<base href="\/Typin\/" \/>/g' src/TypinExamples/TypinExamples/wwwroot/index.html  
     
    # copy index.html to 404.html to serve the same file when a file is not found
    - name: Copy index.html to 404.html
      run: cp src/TypinExamples/TypinExamples/wwwroot/index.html src/TypinExamples/TypinExamples/wwwroot/404.html
     
    # publishes Blazor project to the release-folder
    - name: Publish .NET Core Project
      run: dotnet publish src/TypinExamples/TypinExamples.sln -c Release -o release --nologo -p:PublishTrimmed=false
      
    # add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project. (Allow files and folders starting with an underscore)
    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll
      
    - name: Commit wwwroot to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.7.1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: release/wwwroot
        SINGLE_COMMIT: true
              
