name: CI-Examples

on:
  push:
    branches:
      - develop-examples-app
    tags-ignore:
      - '*'
    paths:
      - 'src/Typin.Examples/*'
    paths-ignore:
      - 'src/Typin/*'
      - LICENSE
      - 'CHANGELOG.md'
      - 'README.md'
  pull_request:
    branches:
      - '*'
    tags-ignore:
      - '*'
    paths:
      - 'src/Typin.Examples/*'
    paths-ignore:
      - 'src/Typing/*'
      - LICENSE
      - 'CHANGELOG.md'
      - 'README.md'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install .NET Core
      uses: actions/setup-dotnet@v1.4.0
      with:
        dotnet-version: 3.1.403

    - name: Build & test
      run: dotnet test src/Typin.Examples/Typin.Examples.sln --configuration Release --logger GitHubActions

    - name: Upload coverage
      uses: codecov/codecov-action@v1.0.5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: src/Typin/Typin.Tests/bin/Release/Coverage.xml

    - name: Upload coverage (analyzers)
      uses: codecov/codecov-action@v1.0.5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: src/Typin/Typin.Analyzers.Tests/bin/Release/Coverage.xml
